sudo: required
dist: trusty
python: "3.6"
services:
  - docker
env:
  global:
    - IMAGE_NAME=sylvance/go-docker
    - secret: "my-secret-squared"

before_script:
  - docker login --username=_ --password=${HEROKU_AUTH_TOKEN} registry.heroku.com
  - docker pull "${IMAGE_NAME}:latest" || true
script:
  - docker build --pull --cache-from "${IMAGE_NAME}:latest" --tag "$IMAGE_NAME" .

after_script:
  - docker images

before_deploy:
  - docker login --username=_ --password=${HEROKU_AUTH_TOKEN} registry.heroku.com
  - git_sha="$(git rev-parse --short HEAD)"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${git_sha}"
deploy:
  - provider: script
    script: docker push "${IMAGE_NAME}:latest"
    on:
      branch: master

  - provider: script
    script: docker push "${IMAGE_NAME}:${git_sha}"
    on:
      branch: develop
