sudo: required
dist: trusty
python: "3.6"
services:
  - docker

env:
  global:
    - IMAGE_NAME=sylvance/go-docker
    - secret: "my-secret-squared"

before_script:
  - docker pull "registry.heroku.com/${IMAGE_NAME}:latest" || true
  - echo -e "machine api.heroku.com\n  login $HEROKU_USERNAME\n  password $HEROKU_PASSWORD\nmachine git.heroku.com\n  login $HEROKU_USERNAME\n  password $HEROKU_PASSWORD" >> ~/.netrc

script:
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - docker build --pull --cache-from "registry.heroku.com/${IMAGE_NAME}:latest" --tag "$IMAGE_NAME" .

after_script:
  - docker images

after_script:
  - docker login --username=_ --password=${HEROKU_AUTH_TOKEN} registry.heroku.com
  - git_sha="$(git rev-parse --short HEAD)"
  - if [ "$TRAVIS_BRANCH" != "master" ] && docker tag "$IMAGE_NAME" "registry.heroku.com/${IMAGE_NAME}:latest"
  - if [ "$TRAVIS_BRANCH" != ${git_sha} ] &&  docker tag "$IMAGE_NAME" "registry.heroku.com/${IMAGE_NAME}:${git_sha}"
  - if [ "$TRAVIS_BRANCH" != "master" ] && docker push "registry.heroku.com/${IMAGE_NAME}:latest" && heroku container:release web -a "${IMAGE_NAME}"
  - if [ "$TRAVIS_BRANCH" != ${git_sha} ] && docker push "registry.heroku.com/${IMAGE_NAME}:${git_sha}" && heroku container:release web -a "${IMAGE_NAME}"
