sudo: required
dist: trusty
python: "3.6"
services:
  - docker

before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - echo -e "machine api.heroku.com\n  login $HEROKU_USERNAME\n  password $HEROKU_AUTH_TOKEN\nmachine git.heroku.com\n  login $HEROKU_USERNAME\n  password $HEROKU_AUTH_TOKEN" >> ~/.netrc
  - heroku container:login

script:
  - heroku container:push web -a ${APP_NAME}

deploy:
  - provider: script
    script: heroku container:release web -a ${APP_NAME} && echo -e "Visit this url to view site ${PROD_URL}"
    on:
      branch: master
