sudo: required
dist: trusty
python: "3.6"
services:
  - docker

before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - echo -e "machine api.heroku.com\n  login $HEROKU_USERNAME\n  password $HEROKU_AUTH_TOKEN\nmachine git.heroku.com\n  login $HEROKU_USERNAME\n  password $HEROKU_AUTH_TOKEN" >> ~/.netrc
  - heroku container:login

script:
  - heroku create
  - heroku container:push web

after_script:
  - heroku container:release web
